[tool.poetry]
name = "ee2"
version = "0.1.0"
description = ""
authors = ["Henning <henning.lorrmann@thws.de>"]
license = "MIT license"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
